seml:
  executable: main.py
  output_dir: configs_seml/logs
  project_root_dir: ../../../..
  conda_environment: gtr

slurm:
  experiments_per_job: 10
  sbatch_options:
    partition: gpu_gtx1080
    gres: gpu:1       # num GPUs
    mem: 32G          # memory
    cpus-per-task: 1  # num cores
    time: 1-00:00     # max time, D-HH:MM
    qos: deadline

# experiment random configs
  
random:
  samples: 30
  seed: 31453

  graphgym.seed:
    seed: 1425
    type: randint
    min: 0
    max: 10000

  graphgym.optim.base_lr:
    seed: 264
    type: loguniform
    min: 1e-5
    max: 1e-1

  graphgym.optim.weight_decay:
    seed: 809
    type: loguniform
    min: 5e-7
    max: 1e-1

  dims_per_head:
    seed: 13094
    type: randint
    min: 3
    max: 17

  graphgym.graphormer.num_layers:
    seed: 357
    type: randint
    min: 2
    max: 13

  graphgym.graphormer.dropout:
    seed: 961
    type: uniform
    min: 0.0
    max: 0.1

  graphgym.graphormer.attention_dropout:
    seed: 661
    type: uniform
    min: 0.1
    max: 0.5

  graphgym.graphormer.mlp_dropout:
    seed: 241
    type: uniform
    min: 0.0
    max: 0.1

  graphgym.posenc_GraphormerBias.num_in_degrees:
    seed: 644
    type: randint
    min: 6
    max: 10

  graphgym.posenc_GraphormerBias.num_spatial_types:
    seed: 5113
    type: randint
    min: 14
    max: 26
  
  graphgym.gnn.layers_post_mp:
    seed: 966
    type: choice
    options:
      - 1
      - 2
      - 3

# experiment fixed configs 

fixed:

  graphgym:

    accelerator: cuda
    out_dir: configs_seml/results
    metric_best: accuracy
    metric_agg: argmax
    tensorboard_each_run: false

    dataset:
      format: PyG-TUDataset
      name: ENZYMES
      task: graph
      task_type: classification
      transductive: false
      split_mode: cv-stratifiedkfold-10
      split_index: 0
      node_encoder: true
      node_encoder_name: LinearNode+WeightedGraphormerBias
      node_encoder_bn: false
      edge_encoder: false

    train:
      mode: custom
      batch_size: 32
      eval_period: 1

    posenc_GraphormerBias:
      enable: true
      node_degrees_only: false
      directed_graphs: false
      has_edge_attr: false
      num_out_degrees: ${config.graphgym.posenc_GraphormerBias.num_in_degrees}

    model:
      type: Graphormer
      loss_fun: cross_entropy
      graph_pooling: graph_token

    graphormer:
      embed_dim: 0  # determined using num_heads and dims_per_head
      input_dropout: 0.0
      num_heads: 8

    gnn:
      head: graphormer_graph
      layers_pre_mp: 0
      dim_inner: 0  # determined using num_heads and dims_per_head

    optim:
      optimizer: adamW
      max_epoch: 500
      scheduler: reduce_on_plateau
      reduce_factor: 0.5
      schedule_patience: 10
      min_lr: 1.0e-5
      early_stopping: true
      early_stopping_patience: 50
      early_stopping_delta_e: 0.02
      early_stopping_warmup: 50
      clip_grad_norm: true
      clip_grad_norm_value: 5.0
      
    attack:
      enable: false
