graphgym:

  accelerator: auto
  out_dir: configs_seml/results
  metric_best: accuracy
  metric_agg: argmax
  tensorboard_each_run: false
  seed: 42

  dataset:
    format: PyG-RobustnessUnitTest
    name: cora_ml
    task: node
    task_type: classification
    transductive: true
    split_mode: standard
    split_index: 0
    node_encoder: true
    node_encoder_name: LinearNode+WeightedGraphormerBias
    node_encoder_bn: false

  posenc_GraphormerBias:
    enable: true
    node_degrees_only: false
    num_spatial_types: 15  # 20  # cora_ml: max cont. = 19, max total = 19
    num_in_degrees: 15  # cora_ml: max cont. = 19, max total = 168
    num_out_degrees: 15
    directed_graphs: false
    has_edge_attr: false
     
 

  train:
    mode: custom
    batch_size: 1
    eval_period: 1
    ckpt_best: true
    enable_ckpt: true
    homophily_regularization: 1.0
    homophily_regularization_gt_weight: 2.0

  model:
    type: Graphormer
    loss_fun: cross_entropy

  graphormer:
    use_graph_token: false
    num_layers: 1
    num_heads: 8
    embed_dim: 56
    dropout: 0.1
    attention_dropout: 0.5  # 0.1
    mlp_dropout: 0.1  # 0.1
    input_dropout: 0.1  # 0.1

  gnn:
    dim_inner: 56
    head: node
    layers_pre_mp: 0
    layers_post_mp: 1

  optim:
    clip_grad_norm: true
    clip_grad_norm_value: 5.0
    optimizer: adamW
    weight_decay: 0.01
    base_lr: 0.05
    max_epoch: 50
    scheduler: cosine_with_warmup
    num_warmup_epochs: 10
    early_stopping: true
    early_stopping_patience: 30
    early_stopping_delta_e: 0.05
    early_stopping_warmup: 30

  attack:
    enable: true
    log_progress: true
    load_best_model: true
    split: test
    num_attacked_graphs: 0  # 0 means attack all
    skip_incorrect_graph_classification: true
    run_random_baseline: true
    epochs: 125
    epochs_resampling: 100
    max_edge_weight_update: 0.0  # 0.0 means no gradient clipping
    lr: 4_000
    block_size: 10_000
    e_budget: 0.15
    minimum_budget: 0
    eps: 1e-7
    is_undirected: false
    prediction_level: node
    loss: tanh_margin
    metric: null
    max_final_samples: 20
    max_trials_sampling: 20
    with_early_stopping: true
    node_prob_enable: true
    node_prob_iterations: 5
    node_prob_log: true
    enable_node_injection: false
    node_injection_from_train: false
    node_injection_from_val: false
    node_injection_from_test: false
    remove_isolated_components: false
    root_node_idx: null
    include_root_nodes_for_injection: true
    existing_node_prob_multiplier: 1  # 1_000
    sample_only_connected: false
    sample_only_trees: false
    allow_existing_graph_pert: true
