graphgym:

  accelerator: auto
  out_dir: configs_seml/results
  metric_best: accuracy
  tensorboard_each_run: false
  seed: 42

  dataset:
    format: PyG-UPFD
    name: politifact-spacy
    task: graph
    task_type: classification_binary
    transductive: false
    split_mode: standard
    node_encoder: true
    node_encoder_name: LinearNode+WeightedGraphormerBias
    node_encoder_bn: false

  posenc_GraphormerBias:
    enable: true
    num_spatial_types: 8
    num_in_degrees: 27
    num_out_degrees: 27
    node_degrees_only: false
    directed_graphs: false
    has_edge_attr: false

  model:
    type: Graphormer
    loss_fun: cross_entropy
    graph_pooling: graph_token

  graphormer:
    num_layers: 2
    num_heads: 2
    embed_dim: 32
    dropout: 0.0
    attention_dropout: 0.0  # 0.1
    mlp_dropout: 0.0  # 0.1
    input_dropout: 0.0  # 0.1

  gnn:
    head: graphormer_graph
    layers_pre_mp: 0
    layers_post_mp: 1
    dim_inner: 32  # `gnn.dim_inner` must match `gt.dim_hidden` / `graphormer.embed_dim`
  
  optim:
    base_lr: 0.001
    weight_decay: 0.01
    clip_grad_norm: true
    clip_grad_norm_value: 5.0
    optimizer: adamW
    max_epoch: 100
    scheduler: cosine_with_warmup
    num_warmup_epochs: 30
    early_stopping: true
    early_stopping_patience: 35
    early_stopping_delta_e: 0.05
    early_stopping_warmup: 30

  train:
    mode: adversarial
    eval_period: 1
    batch_size: 8
    adv:
      batched_train: False
      e_budget: 0.15
      block_size: 1000
      num_replays: 5
      lr: 5000
      # for val
      e_budget_val: 0.05
      block_size_val: 2000
      epochs_val: 12
      lr_val: 4000

  attack:
    enable: true
    e_budget: 0.1
    num_attacked_graphs: 3
    skip_incorrect_graph_classification: false
    log_progress: true
    load_best_model: true
    split: test
    prediction_level: graph
    remove_isolated_components: true
    run_random_baseline: true
    block_size: 1_000  # TODO: test
    epochs: 125  # TODO: test
    epochs_resampling: 100
    resample_period: 1  # TODO: test
    max_final_samples: 20  # TODO: test
    eps: 1.0e-07  # TODO: test
    eps_init_noised: false  # TODO: test
    is_undirected: true
    loss: raw_prediction  # TODO: test
    metric: null
    lr: 4000  # TODO: test
    max_edge_weight_update: 0.0  # TODO: test
    max_trials_sampling: 20
    minimum_budget: 1
    node_prob_enable: true
    node_prob_iterations: 3
    node_prob_log: true
    root_node_idx: 0
    with_early_stopping: true
    node_injection:
      enable: true
      from_train: true
      from_val: true
      from_test: true
      allow_existing_graph_pert: false
      sample_only_connected: true
      include_root_nodes: false
      sample_only_trees: true
    Graphormer:
      use_weighted_degrees: true
      combinations_degree: false
      sp_find_weighted: true
      weight_function: log
      sp_use_weighted: true
      sp_use_gradient: true