seml:
  executable: main.py
  output_dir: configs_seml/logs
  project_root_dir: ../../../..
  conda_environment: gtr

slurm:
  experiments_per_job: 1
  sbatch_options:
    partition: gpu_large
    gres: gpu:1       # num GPUs
    mem: 16G          # memory
    cpus-per-task: 4  # num cores
    time: 1-00:00     # max time, D-HH:MM

# experiment fixed configs

fixed:

  graphgym:

    accelerator: cuda
    out_dir: configs_seml/results
    metric_best: accuracy
    tensorboard_each_run: false

    dataset:
      format: PyG-UPFD
      name: politifact-bert
      task: graph
      task_type: classification_binary
      transductive: false
      split_mode: standard
      node_encoder: true
      node_encoder_name: LinearNode+WeightedRRWPLinear
      node_encoder_bn: false

    posenc_RRWP:
      enable: true
      ksteps: 10
      w_add_dummy_edge: true

    train:
      mode: custom
      batch_size: 16
      eval_period: 1
      enable_ckpt: true
      ckpt_best: true

    model:
      type: GritTransformer
      loss_fun: cross_entropy

    gt:
      layers: 2
      n_heads: 5
      dim_hidden: 50 # `gt.dim_hidden` must match `gnn.dim_inner`
      dropout: 0.0
      attn_dropout: 0.4
      layer_norm: false
      batch_norm: true
      bn_no_runner: false
      bn_momentum: 0.1
      update_e: true
      attn:
        deg_scaler: true
        use_bias: false
        clamp: 5.
        act: relu
        full_attn: true
        norm_e: true
        O_e: true
        edge_enhance: true

    gnn:
      head: weighted_mean_pool_graph
      layers_pre_mp: 0
      layers_post_mp: 1
      dim_inner: 50  # `gnn.dim_inner` must match `gt.dim_hidden` / `graphormer.embed_dim`
    
    optim:
      base_lr: 0.00012
      weight_decay: 1e-5
      clip_grad_norm: true
      clip_grad_norm_value: 5.0
      optimizer: adamW
      max_epoch: 100
      scheduler: cosine_with_warmup
      num_warmup_epochs: 5
      early_stopping: true
      early_stopping_patience: 30
      early_stopping_delta_e: 0.05
      early_stopping_warmup: 30

    attack:
      enable: true
      log_progress: false
      load_best_model: true
      split: test
      num_attacked_graphs: 0  # 0 means attack all
      skip_incorrect_graph_classification: true  # set to true to get transfer attacks for all graphs
      run_random_baseline: true
      epochs: 125
      epochs_resampling: 100
      max_edge_weight_update: 0.0  # 0.0 means no gradient clipping
      lr: 4_000
      block_size: 2000
      e_budget: 0.1
      minimum_budget: 1
      eps: 1e-5
      is_undirected: true
      loss: raw_prediction
      metric: null
      max_final_samples: 20
      max_trials_sampling: 20
      with_early_stopping: true
      node_prob_enable: true
      node_prob_iterations: 5
      node_prob_log: true
      enable_node_injection: true
      node_injection_from_train: true
      node_injection_from_val: true
      node_injection_from_test: true
      remove_isolated_components: true
      root_node_idx: 0
      include_root_nodes_for_injection: false
      existing_node_prob_multiplier: 1  # 1_000
      sample_only_connected: true
      sample_only_trees: true
      allow_existing_graph_pert: false
