seml:
  executable: main.py
  output_dir: configs_seml/logs
  project_root_dir: ../../../..
  conda_environment: gtr

slurm:
  experiments_per_job: 10
  sbatch_options:
    partition: gpu_a100
    gres: gpu:1       # num GPUs
    mem: 64G          # memory
    cpus-per-task: 2  # num cores
    time: 1-00:00     # max time, D-HH:MM
    qos: deadline

grid:

  graphgym.attack.transfer.perturbation_path:
    type: choice
    options:
      - '/ceph/hdd/students/foth/perturbations/CLUSTER/NettackGCN_infl'
      - '/ceph/hdd/students/foth/perturbations/CLUSTER/GCN_infl'
      - '/ceph/hdd/students/foth/perturbations/CLUSTER/GPS_infl'
      - '/ceph/hdd/students/foth/perturbations/CLUSTER/Graphormer_infl'
      - '/ceph/hdd/students/foth/perturbations/CLUSTER/GRIT_infl'
      - '/ceph/hdd/students/foth/perturbations/CLUSTER/Polynormer_infl'
      - '/ceph/hdd/students/foth/perturbations/CLUSTER/SAN_infl'


# experiment fixed configs

fixed:

  graphgym:

    seed: 42

    out_dir: configs_seml/results

    pretrained:
      dir: '/ceph/hdd/students/foth/models/GCN/CLUSTER/0'
      finetune: false

    attack:
      transfer:
        enable: true
      local:
        enable: true
        num_victim_nodes: 3
        sampling_direct_edge_weight: 0
        sampling_indirect_edge_weight: 1
        sampling_other_edge_weight: 0
      cluster_sampling: false
      enable: true
      num_attacked_graphs: 0
      skip_incorrect_graph_classification: false
      log_progress: false
      load_best_model: false
      split: test
      prediction_level: node
      remove_isolated_components: false
      run_random_baseline: false
      is_undirected: true
      minimum_budget: 1
      node_injection:
        enable: false
  
    # copied from pre-trained model

    accelerator: auto
    dataset:
      edge_encoder: false
      format: PyG-GNNBenchmarkDataset
      name: CLUSTER
      node_encoder: true
      node_encoder_bn: false
      node_encoder_name: LinearNode
      split_index: 0
      split_mode: standard
      task: graph
      task_type: classification
      transductive: false
    gnn:
      act: relu
      agg: mean
      batchnorm: true
      dim_inner: 172
      head: inductive_node
      layer_type: gcnconvweighted
      layers_mp: 16
      layers_post_mp: 2
      layers_pre_mp: 0
      stage_type: skipsum
    metric_agg: argmax
    metric_best: accuracy-SBM
    model:
      loss_fun: weighted_cross_entropy
      type: gnn
    optim:
      base_lr: 0.001
      early_stopping: true
      early_stopping_delta_e: 0.01
      early_stopping_patience: 25
      early_stopping_warmup: 40
      lr_decay: 0.1
      max_epoch: 150
      min_lr: 1.0e-05
      momentum: 0.9
      num_warmup_epochs: 50
      optimizer: adam
      reduce_factor: 0.5
      schedule_patience: 5
      scheduler: reduce_on_plateau
    train:
      batch_size: 64
      mode: custom