graphgym:

  accelerator: auto
  out_dir: configs_seml/results
  metric_best: accuracy
  metric_agg: argmax
  seed: 42

  dataset:
    format: PyG-RobustnessUnitTest
    name: cora_ml
    task: node
    task_type: classification
    transductive: true

  train:
    batch_size: 1
    eval_period: 1
    ckpt_best: true
    enable_ckpt: true
    #homophily_regularization: 1.0
    #homophily_regularization_gt_weight: 2.0

  model:
    type: gnn
    loss_fun: cross_entropy

  gnn:
    layers_pre_mp: 1
    layers_mp: 2
    layers_post_mp: 1
    dim_inner: 256
    layer_type: gcnconvweighted
    stage_type: stack
    batchnorm: true
    act: prelu
    dropout: 0.0
    agg: add
    normalize_adj: false

  optim:
    optimizer: adam
    base_lr: 0.005
    max_epoch: 30

  robustness_unit_test:
    enable: true
