graphgym:

  out_dir: configs_seml/results
  metric_best: accuracy-SBM
  tensorboard_each_run: false
  accelerator: auto
  seed: 42

  dataset:
    format: PyG-GNNBenchmarkDataset
    name: PATTERN
    task: graph
    task_type: classification_binary
    transductive: false
    split_mode: standard
    node_encoder: true
    node_encoder_name: WLapPE
    node_encoder_bn: false
    edge_encoder: true
    edge_encoder_name: DummyEdge
    edge_encoder_bn: false
  
  posenc_WLapPE:
    enable: true
    eigen:
      laplacian_norm: sym
      eigvec_norm: L2
      max_freqs: 10
      use_gradient: true
      correct_pert_eigvec_sign: false
      straight_through_estimator: true
    dim_pe: 16
    layers: 3
    n_heads: 4
    raw_norm_type: none
    post_layers: 0
    pass_as_var: false
  
  train:
    mode: custom
    batch_size: 16
    eval_period: 1

  model:
    type: WeightedSANTransformer
    loss_fun: weighted_cross_entropy

  gt:
    layers: 6
    n_heads: 4
    dim_hidden: 64  # `gt.dim_hidden` must match `gnn.dim_inner`
    full_graph: true
    gamma: 1e-2
    gamma_learnable: false
    dropout: 0.0
    layer_norm: false
    batch_norm: true
    residual: true
    wsan_add_dummy_edges: true
    attn:
      use_bias: false
      clamp: 5.0

  gnn:
    head: inductive_node
    layers_pre_mp: 0
    layers_post_mp: 1
    dim_inner: 64  # `gt.dim_hidden` must match `gnn.dim_inner`
    
  optim:
    optimizer: adam
    weight_decay: 0.0
    base_lr: 0.0005
    max_epoch: 1000
    scheduler: reduce_on_plateau
    reduce_factor: 0.5
    schedule_patience: 10
    min_lr: 1e-6

  attack:
    enable: true
    log_progress: true
    load_best_model: true
    split: test
    num_attacked_graphs: 0  # 0 means attack all
    skip_incorrect_graph_classification: true
    run_random_baseline: true
    epochs: 125
    epochs_resampling: 100
    max_edge_weight_update: 0.0  # 0.0 means no gradient clipping
    lr: 4_000
    block_size: 800
    e_budget: 0.1
    minimum_budget: 0
    eps: 1e-5
    is_undirected: true
    prediction_level: node
    loss: tanh_margin
    metric: null
    max_final_samples: 20
    max_trials_sampling: 20
    with_early_stopping: true
    node_prob_enable: true
    node_prob_iterations: 5
    node_prob_log: true
    enable_node_injection: false
    node_injection_from_train: false
    node_injection_from_val: false
    node_injection_from_test: false
    remove_isolated_components: false
    root_node_idx: null
    include_root_nodes_for_injection: true
    existing_node_prob_multiplier: 1  # 1_000
    sample_only_connected: false
    sample_only_trees: false
    allow_existing_graph_pert: true
