graphgym:

  accelerator: auto
  out_dir: configs_seml/results
  metric_best: accuracy
  tensorboard_each_run: false
  seed: 42

  dataset:
    format: PyG-UPFD
    name: politifact-spacy
    task: graph
    task_type: classification_binary
    transductive: false
    split_mode: standard
    node_encoder: true
    node_encoder_name: LinearNode+WeightedRRWPLinear
    node_encoder_bn: false

  posenc_RRWP:
    enable: true
    ksteps: 5
    w_add_dummy_edge: true

  train:
    mode: custom
    batch_size: 8
    eval_period: 1
    enable_ckpt: true
    ckpt_best: true

  model:
    type: GritTransformer
    loss_fun: cross_entropy

  gt:
    layers: 1
    n_heads: 2
    dim_hidden: 4 # `gt.dim_hidden` must match `gnn.dim_inner`
    dropout: 0.0
    attn_dropout: 0.0
    layer_norm: false
    batch_norm: true
    bn_no_runner: false  # false (true for debugging / reproducibility)
    update_e: true
    attn:
      deg_scaler: true
      use_bias: false
      clamp: 5.
      act: relu
      full_attn: true
      norm_e: true
      O_e: true
      edge_enhance: true

  gnn:
    head: weighted_mean_pool_graph
    layers_pre_mp: 0
    layers_post_mp: 1
    dim_inner: 4  # `gnn.dim_inner` must match `gt.dim_hidden` / `graphormer.embed_dim`
  
  optim:
    base_lr: 0.0001
    weight_decay: 0.01
    clip_grad_norm: true
    clip_grad_norm_value: 5.0
    optimizer: adamW
    max_epoch: 1  # 70
    scheduler: cosine_with_warmup
    num_warmup_epochs: 15
    early_stopping: true
    early_stopping_patience: 35
    early_stopping_delta_e: 0.05
    early_stopping_warmup: 30

  attack:
    enable: true
    log_progress: true
    load_best_model: true
    split: test
    num_attacked_graphs: 0  # 0 means attack all
    skip_incorrect_graph_classification: true
    run_random_baseline: true
    epochs: 125
    epochs_resampling: 100
    max_edge_weight_update: 0.0  # 0.0 means no gradient clipping
    lr: 4_000
    block_size: 500
    e_budget: 0.1
    minimum_budget: 0
    eps: 1e-4
    is_undirected: true
    loss: reflected_cross_entropy  # raw_prediction
    metric: null
    max_final_samples: 20
    max_trials_sampling: 20
    with_early_stopping: true
    node_prob_enable: true
    node_prob_iterations: 5
    node_prob_log: true
    enable_node_injection: true
    node_injection_from_train: true
    node_injection_from_val: true
    node_injection_from_test: true
    remove_isolated_components: true
    root_node_idx: 0
    include_root_nodes_for_injection: false
    existing_node_prob_multiplier: 1  # 1_000
    sample_only_connected: true
    sample_only_trees: true
    allow_existing_graph_pert: false