graphgym:

  accelerator: auto
  out_dir: configs_seml/results
  metric_best: accuracy
  metric_agg: argmax
  tensorboard_each_run: false
  seed: 42

  dataset:
    format: PyG-UPFD
    name: politifact-spacy
    task: graph
    task_type: classification_binary
    transductive: false
    split_mode: standard
    node_encoder: true
    node_encoder_name: LinearNode+WeightedGraphormerBias
    node_encoder_bn: false

  posenc_GraphormerBias:
    enable: true
    node_degrees_only: false
    num_spatial_types: 16
    num_in_degrees: 32
    num_out_degrees: 32
    directed_graphs: false
    has_edge_attr: false
    # next 2 only matter for attack, set to fixed false
    combinations_degree: false
    use_weighted_path_distance: true

  train:
    mode: custom
    batch_size: 16
    eval_period: 1
    ckpt_best: true
    enable_ckpt: true

  model:
    type: Graphormer
    loss_fun: cross_entropy
    graph_pooling: graph_token

  graphormer:
    num_layers: 2
    num_heads: 2
    embed_dim: 32
    dropout: 0.0
    attention_dropout: 0.0  # 0.1
    mlp_dropout: 0.0  # 0.1
    input_dropout: 0.0  # 0.1

  gnn:
    dim_inner:  32
    head: graphormer_graph
    layers_pre_mp: 0
    layers_post_mp: 2

  optim:
    clip_grad_norm: true
    clip_grad_norm_value: 5.0
    optimizer: adamW
    weight_decay: 0.01
    base_lr: 0.05
    max_epoch: 3
    scheduler: cosine_with_warmup
    num_warmup_epochs: 10
    early_stopping: true
    early_stopping_patience: 30
    early_stopping_delta_e: 0.05
    early_stopping_warmup: 30

  attack:
    enable: true
    split: test
    num_attacked_graphs: 0  # 0 means attack all
    lr: 4_000
    block_size: 2_000
    e_budget: 0.1
    is_undirected: true
    loss: train
    enable_node_injection: true
    node_injection_from_train: true
    node_injection_from_val: true
    node_injection_from_test: true
    existing_node_prob_multiplier: 1  # 1_000
    allow_existing_graph_pert: false
    remove_isolated_components: true
    root_node_idx: 0
    include_root_nodes_for_injection: false
    sample_only_connected: true
    sample_only_trees: true
