graphgym:

  out_dir: configs_seml/results
  metric_best: accuracy-SBM
  tensorboard_each_run: false
  accelerator: auto
  seed: 42

  dataset:
    format: PyG-GNNBenchmarkDataset
    name: PATTERN
    task: graph
    task_type: classification_binary
    transductive: false
    split_mode: standard
    node_encoder: true
    node_encoder_name: LinearNode+WeightedGraphormerBias
    node_encoder_bn: false
    edge_encoder: false

  posenc_GraphormerBias:
    enable: true
    num_spatial_types: 32
    num_in_degrees: 32
    num_out_degrees: 32
    node_degrees_only: false
    directed_graphs: false
    has_edge_attr: false
    combinations_degree: false
    use_weighted_path_distance: true

  train:
    mode: custom
    batch_size: 32
    eval_period: 1

  model:
    type: Graphormer
    loss_fun: weighted_cross_entropy

  graphormer:
    num_layers: 10
    num_heads: 8
    embed_dim: 256
    dropout: 0.0
    attention_dropout: 0.3  # 0.1
    mlp_dropout: 0.1  # 0.1
    input_dropout: 0.0  # 0.1
    use_graph_token: false

  gnn:
    head: inductive_node
    layers_pre_mp: 0
    layers_post_mp: 2
    dim_inner: 256  # `gt.dim_hidden` must match `gnn.dim_inner`

  optim:
    clip_grad_norm: true
    optimizer: adamW
    weight_decay: 0.0  # 1e-5
    base_lr: 0.0001
    max_epoch: 60
    scheduler: cosine_with_warmup
    num_warmup_epochs: 15
    early_stopping: true
    early_stopping_patience: 20
    early_stopping_delta_e: 0.05
    early_stopping_warmup: 20

  attack:
    enable: true
    log_progress: true
    load_best_model: true
    split: test
    num_attacked_graphs: 0  # 0 means attack all
    skip_incorrect_graph_classification: true
    run_random_baseline: true
    epochs: 125
    epochs_resampling: 100
    max_edge_weight_update: 0.0  # 0.0 means no gradient clipping
    lr: 4_000
    block_size: 800
    e_budget: 0.1
    minimum_budget: 0
    eps: 1e-5
    is_undirected: true
    prediction_level: node
    loss: tanh_margin
    metric: null
    max_final_samples: 20
    max_trials_sampling: 20
    with_early_stopping: true
    node_prob_enable: true
    node_prob_iterations: 5
    node_prob_log: true
    enable_node_injection: false
    node_injection_from_train: false
    node_injection_from_val: false
    node_injection_from_test: false
    remove_isolated_components: false
    root_node_idx: null
    include_root_nodes_for_injection: true
    existing_node_prob_multiplier: 1  # 1_000
    sample_only_connected: false
    sample_only_trees: false
    allow_existing_graph_pert: true
