graphgym:

  out_dir: configs_seml/results
  metric_best: accuracy-SBM
  tensorboard_each_run: false
  accelerator: auto
  seed: 42
  
  dataset:
    format: PyG-GNNBenchmarkDataset
    name: PATTERN
    task: graph
    task_type: classification_binary
    transductive: false
    split_mode: standard
    node_encoder: true
    node_encoder_name: LinearNode+WeightedRRWPLinear
    node_encoder_bn: false
    edge_encoder: false

  posenc_RRWP:
    enable: true
    ksteps: 5  # 12

  train:
    mode: custom
    batch_size: 32
    eval_period: 1

  model:
    type: GritTransformer
    loss_fun: weighted_cross_entropy

  gt:
    layers: 6
    n_heads: 4
    dim_hidden: 64 # `gt.dim_hidden` must match `gnn.dim_inner`
    dropout: 0.0
    attn_dropout: 0.2
    layer_norm: false
    batch_norm: true
    bn_momentum: 0.1
    bn_no_runner: true  # false (true for debugging / reproducibility)
    update_e: true
    attn:
      deg_scaler: true
      use_bias: false
      clamp: 5.
      act: relu
      full_attn: true
      norm_e: true
      O_e: true
      edge_enhance: true

  gnn:
    head: inductive_node
    layers_pre_mp: 0
    layers_post_mp: 1
    dim_inner: 64  # `gt.dim_hidden` must match `gnn.dim_inner`

  optim:
    clip_grad_norm: true
    optimizer: adamW
    weight_decay: 0.0  # 1e-5
    base_lr: 0.007
    max_epoch: 50
    scheduler: cosine_with_warmup
    num_warmup_epochs: 5
    early_stopping: true
    early_stopping_patience: 35
    early_stopping_delta_e: 0.05
    early_stopping_warmup: 30

  attack:
    enable: true
    log_progress: true
    load_best_model: true
    split: test
    num_attacked_graphs: 0  # 0 means attack all
    skip_incorrect_graph_classification: true
    run_random_baseline: true
    epochs: 125
    epochs_resampling: 100
    lr: 4_000
    block_size: 800
    e_budget: 0.1
    minimum_budget: 0
    eps: 1e-5
    is_undirected: true
    prediction_level: node
    loss: tanh_margin
    metric: null
    max_final_samples: 20
    max_trials_sampling: 20
    with_early_stopping: true
    node_prob_enable: true
    node_prob_iterations: 5
    node_prob_log: true
    enable_node_injection: false
    node_injection_from_train: false
    node_injection_from_val: false
    node_injection_from_test: false
    remove_isolated_components: false
    root_node_idx: null
    include_root_nodes_for_injection: true
    existing_node_prob_multiplier: 1  # 1_000
    sample_only_connected: false
    sample_only_trees: false
    allow_existing_graph_pert: true
