graphgym:

  accelerator: auto
  out_dir: configs_seml/results
  metric_best: accuracy
  metric_agg: argmax
  seed: 42

  dataset:
    format: PyG-RobustnessUnitTest
    name: cora_ml
    task: node
    task_type: classification
    transductive: true

  train:
    batch_size: 1
    eval_period: 1
    ckpt_best: true
    enable_ckpt: true

  model:
    type: gnn
    loss_fun: cross_entropy

  gnn:
    layers_pre_mp: 1
    layers_mp: 2
    layers_post_mp: 1
    dim_inner: 256
    layer_type: gcnconvweighted
    stage_type: stack
    batchnorm: true
    act: prelu
    dropout: 0.0
    agg: add
    normalize_adj: false

  optim:
    optimizer: adam
    base_lr: 0.005
    max_epoch: 15

  attack:
    enable: true
    log_progress: true
    load_best_model: true
    split: test
    num_attacked_graphs: 0  # 0 means attack all
    skip_incorrect_graph_classification: true
    run_random_baseline: true
    epochs: 125
    epochs_resampling: 100
    max_edge_weight_update: 0.0  # 0.0 means no gradient clipping
    lr: 4_000
    block_size: 10_000
    e_budget: 0.15
    minimum_budget: 0
    eps: 1e-7
    is_undirected: false
    prediction_level: node
    loss: raw_prediction
    metric: null
    max_final_samples: 20
    max_trials_sampling: 20
    with_early_stopping: true
    node_prob_enable: false
    node_prob_iterations: 5
    node_prob_log: true
    enable_node_injection: false
    node_injection_from_train: false
    node_injection_from_val: false
    node_injection_from_test: false
    remove_isolated_components: false
    root_node_idx: null
    include_root_nodes_for_injection: true
    existing_node_prob_multiplier: 1  # 1_000
    sample_only_connected: false
    sample_only_trees: false
    allow_existing_graph_pert: true
