seml:
  executable: main.py
  output_dir: configs_seml/logs
  project_root_dir: ../../../..
  conda_environment: gtr

slurm:
  experiments_per_job: 6
  sbatch_options:
    partition: gpu_a100
    gres: gpu:1       # num GPUs
    mem: 32G          # memory
    cpus-per-task: 16  # num cores
    time: 1-00:00     # max time, D-HH:MM

# Hyperparameter search

random:
  samples: 30
  seed: 18753

  graphgym.seed:
    seed: 5721
    type: randint
    min: 0
    max: 10000

  dims_per_head:
    seed: 3522
    type: randint
    min: 12
    max: 22

# experiment fixed configs

fixed:

  graphgym:

    accelerator: cuda
    out_dir: configs_seml/results
    metric_best: accuracy-SBM
    metric_agg: argmax
    tensorboard_each_run: false

    dataset:
      format: PyG-GNNBenchmarkDataset
      name: CLUSTER
      task: graph
      task_type: classification
      transductive: false
      split_mode: standard
      node_encoder: true
      node_encoder_name: WLapPE
      node_encoder_bn: false

    train:
      mode: custom
      eval_period: 1
      batch_size: 64

    model:
      type: GPSModel
      loss_fun: weighted_cross_entropy

    posenc_WLapPE:
      enable: true
      dim_pe: 16
      layers: 2
      model: DeepSet
      eigen:
        eigvec_norm: L2
        laplacian_norm: sym
        max_freqs: 10
      pass_as_var: false
      post_layers: 0
      raw_norm_type: none

    gt:
      layer_type: WeightedGCN+Transformer
      layers: 16
      dim_hidden: 0  # determined using num_heads and dims_per_head
      layer_norm: false
      batch_norm: true
      dropout: 0.05
      attn_dropout: 0.5
      n_heads: 8

    gnn:
      batchnorm: true
      act: relu
      head: inductive_node
      layers_pre_mp: 0
      layers_post_mp: 2
      dim_inner: 0  # determined using num_heads and dims_per_head

    optim:
      optimizer: adam
      weight_decay: 0.0
      max_epoch: 170
      base_lr: 0.003
      scheduler: reduce_on_plateau
      reduce_factor: 0.5
      schedule_patience: 5
      min_lr: 1.0e-5
      clip_grad_norm: false
      early_stopping: true
      early_stopping_patience: 30
      early_stopping_delta_e: 0.01
      early_stopping_warmup: 30

    attack:
      enable: false
