seml:
  executable: main.py
  output_dir: configs_seml/logs
  project_root_dir: ../../../..
  conda_environment: gtr

slurm:
  experiments_per_job: 16
  sbatch_options:
    partition: gpu_a100
    gres: gpu:1       # num GPUs
    mem: 48G          # memory
    cpus-per-task: 16  # num cores
    time: 1-00:00     # max time, D-HH:MM

# Hyperparameter search

random:
  samples: 80
  seed: 187

  graphgym.seed:
    seed: 786
    type: randint
    min: 0
    max: 10000

  graphgym.optim.base_lr:
    seed: 2264
    type: loguniform
    min: 3.0e-4
    max: 8.0e-3

  graphgym.optim.weight_decay:
    seed: 89
    type: loguniform
    min: 1.0e-9
    max: 1.0e-6

  dims_per_head:
    seed: 164
    type: randint
    min: 3
    max: 7

  graphgym.gt.layers:
    seed: 357
    type: randint
    min: 8
    max: 17

  graphgym.gnn.layers_post_mp:
    seed: 96624
    type: choice
    options:
      - 1
      - 2

# experiment fixed configs

fixed:

  graphgym:

    accelerator: cuda
    out_dir: configs_seml/results
    metric_best: accuracy-SBM
    metric_agg: argmax
    tensorboard_each_run: false

    dataset:
      format: PyG-GNNBenchmarkDataset
      name: CLUSTER
      task: graph
      task_type: classification
      transductive: false
      split_mode: standard
      node_encoder: true
      node_encoder_name: WLapPE
      node_encoder_bn: false

    train:
      mode: custom
      eval_period: 1
      batch_size: 64

    model:
      type: GPSModel
      loss_fun: weighted_cross_entropy

    posenc_WLapPE:
      enable: true
      dim_pe: 16
      layers: 2
      model: DeepSet
      eigen:
        eigvec_norm: L2
        laplacian_norm: sym
        max_freqs: 10
      pass_as_var: false
      post_layers: 0
      raw_norm_type: none

    gt:
      layer_type: WeightedGCN+Transformer
      dim_hidden: 0  # determined using num_heads and dims_per_head
      layer_norm: false
      batch_norm: true
      dropout: 0.05
      attn_dropout: 0.4
      n_heads: 8

    gnn:
      batchnorm: true
      act: relu
      head: inductive_node
      layers_pre_mp: 0
      dim_inner: 0  # determined using num_heads and dims_per_head

    optim:
      clip_grad_norm: true
      clip_grad_norm_value: 5.0
      optimizer: adamW
      max_epoch: 100
      scheduler: cosine_with_warmup
      num_warmup_epochs: 5
      early_stopping: true
      early_stopping_patience: 30
      early_stopping_delta_e: 0.02
      early_stopping_warmup: 30

    attack:
      enable: false
