graphgym:

  out_dir: configs_seml/results
  metric_best: accuracy-SBM
  tensorboard_each_run: false
  accelerator: auto
  seed: 42

  dataset:
    format: PyG-GNNBenchmarkDataset
    name: CLUSTER
    task: graph
    task_type: classification
    transductive: false
    split_mode: standard
    node_encoder: true
    node_encoder_name: LinearNode+WeightedRRWPLinear
    node_encoder_bn: false

  posenc_RRWP:
    enable: true
    ksteps: 4  # 32
    w_add_dummy_edge: true
  
  train:
    mode: custom
    batch_size: 16
    eval_period: 1

  model:
    type: GritTransformer
    loss_fun: weighted_cross_entropy

  gt:
    layers: 2  # 16
    n_heads: 2  # 8
    dim_hidden: 8  # 48
    dropout: 0.01
    attn_dropout: 0.5
    layer_norm: false
    batch_norm: true
    update_e: true
    attn:
      deg_scaler: true
      use_bias: false
      clamp: 5.
      act: relu
      full_attn: true
      norm_e: true
      O_e: true
      edge_enhance: true

  gnn:
    head: inductive_node
    layers_pre_mp: 0
    layers_post_mp: 1  # 3
    dim_inner: 8  # 48

  optim:
    clip_grad_norm: true
    optimizer: adamW
    weight_decay: 1.0e-5
    base_lr: 0.001
    max_epoch: 100
    scheduler: cosine_with_warmup
    num_warmup_epochs: 5
    early_stopping: true
    early_stopping_patience: 35
    early_stopping_delta_e: 0.05
    early_stopping_warmup: 30

  attack:
    enable: true
    log_progress: true
    load_best_model: true
    split: test
    num_attacked_graphs: 0  # 0 means attack all
    skip_incorrect_graph_classification: true
    run_random_baseline: true
    epochs: 125
    epochs_resampling: 100
    max_edge_weight_update: 0.0  # 0.0 means no gradient clipping
    lr: 4_000
    block_size: 800
    e_budget: 0.1
    minimum_budget: 0
    eps: 1e-5
    is_undirected: true
    prediction_level: node
    loss: tanh_margin
    metric: null
    max_final_samples: 20
    max_trials_sampling: 20
    with_early_stopping: true
    node_prob_enable: false
    node_prob_iterations: 2
    node_prob_log: true
    enable_node_injection: false
    node_injection_from_train: false
    node_injection_from_val: false
    node_injection_from_test: false
    remove_isolated_components: false
    root_node_idx: null
    include_root_nodes_for_injection: true
    existing_node_prob_multiplier: 1  # 1_000
    sample_only_connected: false
    sample_only_trees: false
    allow_existing_graph_pert: true