graphgym:

  out_dir: configs_seml/results
  metric_best: accuracy-SBM
  tensorboard_each_run: false
  accelerator: auto
  seed: 42

  dataset:
    format: PyG-GNNBenchmarkDataset
    name: CLUSTER
    task: graph
    task_type: classification
    transductive: false
    split_mode: standard
    node_encoder: true
    node_encoder_name: LinearNode
    node_encoder_bn: false
    edge_encoder: false

  train:
    mode: custom
    batch_size: 32
    eval_period: 1

  model:
    type: WeightedPolynormer
    loss_fun: weighted_cross_entropy

  gnn:
    head: inductive_node
    layers_pre_mp: 0
    layers_mp: 10
    att_heads: 8
    layers_post_mp: 2
    dim_inner: 128
    dropout: 0.2
  
  gt:
    layers: 3
    n_heads: 8
    dropout: 0.1
    polynormer:
      dropout_node_input: 0.0
      local_pre_layer_norm: false
      beta: -1.0
      qk_shared: true

  optim:
    clip_grad_norm: true
    optimizer: adamW
    weight_decay: 1.0e-5
    max_epoch: 10
    num_local_epochs: 0
    scheduler: cosine_with_warmup
    base_lr: 0.0005
    num_warmup_epochs: 5
    early_stopping: true
    early_stopping_patience: 40
    early_stopping_delta_e: 0.0
    early_stopping_warmup: 20

  attack:
    e_budget: 0.05
    cluster_sampling: false
    enable: true
    num_attacked_graphs: 3  # 50
    skip_incorrect_graph_classification: false
    log_progress: true
    load_best_model: false
    split: test
    prediction_level: node
    remove_isolated_components: false
    run_random_baseline: true
    block_size: 2000  # 20_000
    epochs: 125
    epochs_resampling: 100
    resample_period: 1
    max_final_samples: 20
    eps: 1.0e-07
    eps_init_noised: false
    is_undirected: true
    loss: tanh_margin
    metric: neg_accuracy
    lr: 4000
    max_edge_weight_update: 0.0
    max_trials_sampling: 20
    minimum_budget: 1
    node_prob_enable: false
    root_node_idx: null
    with_early_stopping: true
    node_injection:
      enable: false
