graphgym:

  seed: 42

  accelerator: auto  # cuda
  out_dir: configs_seml/results
  metric_best: accuracy-SBM
  metric_agg: argmax
  tensorboard_each_run: false

  dataset:
    format: PyG-GNNBenchmarkDataset
    name: CLUSTER
    task: graph
    task_type: classification
    transductive: false
    split_mode: standard
    node_encoder: true
    node_encoder_name: WLapPE
    node_encoder_bn: false
    edge_encoder: True
    edge_encoder_name: WeightedDummyEdge
    edge_encoder_bn: False

  train:
    mode: custom
    eval_period: 1
    batch_size: 16

  model:
    type: GPSModel
    loss_fun: weighted_cross_entropy

  posenc_WLapPE:
    enable: true
    dim_pe: 16
    layers: 2
    model: DeepSet
    eigen:
      eigvec_norm: L2
      laplacian_norm: sym
      max_freqs: 10
    pass_as_var: false
    post_layers: 0
    raw_norm_type: none

  gt:
    layer_type: WeightedGatedGCN+Transformer
    layers: 3  # 16
    dim_hidden: 20  # 48
    layer_norm: false
    batch_norm: true
    dropout: 0.1
    attn_dropout: 0.5
    n_heads: 4  # 8

  gnn:
    batchnorm: true
    act: relu
    head: inductive_node
    layers_pre_mp: 0
    layers_post_mp: 1  # 3
    dim_inner: 20  # 48

  optim:
    clip_grad_norm: true
    optimizer: adamW
    weight_decay: 1.0e-5
    max_epoch: 5
    scheduler: cosine_with_warmup
    base_lr: 0.0005
    num_warmup_epochs: 5
    early_stopping: true
    early_stopping_patience: 40
    early_stopping_delta_e: 0.0
    early_stopping_warmup: 20

  attack:
    e_budget: 0.05
    cluster_sampling: false
    enable: true
    num_attacked_graphs: 3  # 50
    skip_incorrect_graph_classification: false
    log_progress: true
    load_best_model: false
    split: test
    prediction_level: node
    remove_isolated_components: false
    run_random_baseline: true
    block_size: 2000  # 20_000
    epochs: 125
    epochs_resampling: 100
    resample_period: 1
    max_final_samples: 20
    eps: 1.0e-07
    eps_init_noised: false
    is_undirected: true
    loss: tanh_margin
    metric: neg_accuracy
    lr: 4000
    max_edge_weight_update: 0.0
    max_trials_sampling: 20
    minimum_budget: 1
    node_prob_enable: false
    root_node_idx: null
    with_early_stopping: true
    node_injection:
      enable: false
    SAN:
      eps_repeated_eigenvalue: 1.0e-5
      enable_pert_grad: false
      enable_eig_backprop: false
      eig_backprop_separation_pert: 1.0e-4
      set_first_pert_zero: true
      nia_pert: full
      pert_BPDA: false
      match_true_signs: false
      match_true_eigenspaces: false
    GPS:
      grad_MPNN: true
