graphgym:

  out_dir: configs_seml/results
  metric_best: accuracy-SBM
  tensorboard_each_run: false
  accelerator: auto
  seed: 42

  dataset:
    format: PyG-GNNBenchmarkDataset
    name: CLUSTER
    task: graph
    task_type: classification
    transductive: false
    split_mode: standard
    node_encoder: true
    node_encoder_name: LinearNode
    node_encoder_bn: false
    edge_encoder: false

  model:
    type: gnn
    loss_fun: weighted_cross_entropy

  gnn:
    layer_type: gcnconvweighted
    stage_type: skipsum
    head: inductive_node
    layers_pre_mp: 0
    layers_mp: 4  # 16
    layers_post_mp: 1  # 2
    dim_inner: 32  # 172
    batchnorm: true
    act: relu
    dropout: 0.0

  optim:
    optimizer: adam
    weight_decay: 0.0
    base_lr: 0.001
    max_epoch: 60
    scheduler: reduce_on_plateau
    reduce_factor: 0.5
    schedule_patience: 5
    min_lr: 1.0e-5
    clip_grad_norm: false
    early_stopping: true
    early_stopping_patience: 30
    early_stopping_delta_e: 0.01
    early_stopping_warmup: 30

  train:
    mode: adversarial
    eval_period: 1
    batch_size: 8
    adv:
      batched_train: True
      e_budget: 0.05
      block_size: 1000
      num_replays: 6
      lr: 5000
      # for val
      e_budget_val: 0.05
      block_size_val: 2000
      epochs_val: 12
      lr_val: 4000
    
  attack:
    enable: true
    num_attacked_graphs: 0
    skip_incorrect_graph_classification: false
    log_progress: true
    load_best_model: true
    split: test
    prediction_level: node
    remove_isolated_components: false
    run_random_baseline: false
    e_budget: 0.05
    block_size: 1000
    epochs: 125
    epochs_resampling: 100
    resample_period: 1
    max_final_samples: 20
    eps: 1.0e-07
    eps_init_noised: false
    is_undirected: true
    loss: tanh_margin
    metric: neg_accuracy
    lr: 4000
    max_edge_weight_update: 0.0
