graphgym:

  out_dir: configs_seml/results
  metric_best: accuracy-SBM
  tensorboard_each_run: false
  accelerator: auto
  seed: 42

  dataset:
    format: PyG-GNNBenchmarkDataset
    name: CLUSTER
    task: graph
    task_type: classification
    transductive: false
    split_mode: standard
    node_encoder: true
    node_encoder_name: LinearNode
    node_encoder_bn: false
    edge_encoder: false

  train:
    mode: custom
    batch_size: 3
    eval_period: 1

  model:
    type: gnn
    loss_fun: weighted_cross_entropy

  gnn:
    layer_type: gcnconvweighted
    stage_type: stack
    head: inductive_node
    layers_pre_mp: 0
    layers_mp: 1
    layers_post_mp: 2
    dim_inner: 40
    batchnorm: true
    act: relu
    dropout: 0.0
    agg: add  # mean
    normalize_adj: false

  optim:
    clip_grad_norm: true
    clip_grad_norm_value: 5.0
    optimizer: adamW
    weight_decay: 1.0e-5
    base_lr: 0.001
    max_epoch: 10
    scheduler: cosine_with_warmup
    num_warmup_epochs: 5
    early_stopping: true
    early_stopping_patience: 35
    early_stopping_delta_e: 0.05
    early_stopping_warmup: 30
    
  attack:
    enable: true
    num_attacked_graphs: 0
    skip_incorrect_graph_classification: false
    log_progress: true
    load_best_model: false
    split: test
    prediction_level: node
    remove_isolated_components: false
    run_random_baseline: true
    e_budget: 0.05
    block_size: 1000  # TODO: test
    epochs: 125  # TODO: test
    epochs_resampling: 100
    resample_period: 1  # TODO: test
    max_final_samples: 20  # TODO: test
    eps: 1.0e-07  # TODO: test
    eps_init_noised: false  # TODO: test
    is_undirected: true
    loss: tanh_margin  # TODO: test
    metric: neg_accuracy
    lr: 4000  # TODO: test
    max_edge_weight_update: 0.0  # TODO: test
    max_trials_sampling: 20
    minimum_budget: 1
    node_prob_enable: false
    root_node_idx: null
    with_early_stopping: true
    cluster_sampling: true  # don't modify edges to labeled nodes
    node_injection:
      enable: false
