graphgym:

  out_dir: configs_seml/results
  metric_best: accuracy
  tensorboard_each_run: false
  accelerator: auto
  seed: 42

  dataset:
    format: PyG-TUDataset
    name: MUTAG
    task: graph
    task_type: classification_binary
    transductive: false
    split_mode: cv-stratifiedkfold-3
    split_index: 0
    node_encoder: true
    node_encoder_name: LinearNode
    node_encoder_bn: false
    edge_encoder: false

  train:
    mode: custom
    batch_size: 32
    eval_period: 1

  model:
    type: gnn
    loss_fun: cross_entropy

  gnn:
    layer_type: gcnconvweighted
    stage_type: stack
    head: weighted_add_pool_graph
    layers_pre_mp: 0
    layers_mp: 3
    layers_post_mp: 1
    dim_inner: 16
    batchnorm: true
    act: relu
    dropout: 0.0
    agg: mean
    normalize_adj: false

  optim:
    base_lr: 0.001
    weight_decay: 0.0
    clip_grad_norm: false
    optimizer: adam
    max_epoch: 100
    scheduler: reduce_on_plateau
    reduce_factor: 0.5
    schedule_patience: 5
    min_lr: 1.0e-5
    early_stopping: true
    early_stopping_patience: 30
    early_stopping_delta_e: 0.05
    early_stopping_warmup: 30
    
  attack:
    enable: true
    num_attacked_graphs: 20
    skip_incorrect_graph_classification: false
    log_progress: true
    load_best_model: true
    split: test
    prediction_level: graph
    remove_isolated_components: false
    run_random_baseline: true
    e_budget: 0.1
    minimum_budget: 1
    block_size: 500
    epochs: 125
    epochs_resampling: 100
    resample_period: 1
    max_final_samples: 20
    eps: 1.0e-07
    eps_init_noised: false
    is_undirected: true
    loss: raw_prediction
    lr: 4_000
    max_edge_weight_update: 0.0  # 0.0 means no gradient clipping
