graphgym:

  out_dir: configs_seml/results
  metric_best: auc
  tensorboard_each_run: false
  accelerator: auto
  seed: 42
  out_dir: results

  dataset:
    format: OGB
    name: ogbg-molhiv
    task: graph
    task_type: classification_binary
    transductive: False
    node_encoder: True
    node_encoder_name: Atom #+LinearNode
    node_encoder_bn: False
    edge_encoder: False
    #edge_encoder_name: Bond
    #edge_encoder_bn: False

  train:
    mode: custom
    batch_size: 32
    eval_period: 1

  model:
    type: gnn
    loss_fun: cross_entropy
    
  gnn:
    head: weighted_add_pool_graph
    layer_type: gcnconvweighted
    stage_type: skipsum
    layers_mp: 3
    layers_pre_mp: 0
    layers_post_mp: 1
    dim_inner: 32
    batchnorm: True
    act: relu
    dropout: 0.0
    agg: mean
    normalize_adj: False

  optim:
    clip_grad_norm: True
    optimizer: adamW
    weight_decay: 1.0e-5
    base_lr: 0.0001
    max_epoch: 1
    scheduler: cosine_with_warmup
    num_warmup_epochs: 5

  attack:
    enable: true
    num_attacked_graphs: 20
    skip_incorrect_graph_classification: false
    log_progress: true
    load_best_model: true
    split: test
    prediction_level: graph
    remove_isolated_components: false
    run_random_baseline: true
    e_budget: 0.05
    block_size: 2_000
    epochs: 125
    epochs_resampling: 100
    resample_period: 1
    max_final_samples: 20
    eps: 1.0e-07
    eps_init_noised: false
    is_undirected: true
    loss: raw_prediction
    lr: 4_000
    max_edge_weight_update: 0.0  # 0.0 means no gradient clipping