graphgym:

  out_dir: configs_seml/results
  metric_best: accuracy
  tensorboard_each_run: false
  accelerator: auto
  seed: 42

  dataset:
    format: PyG-TUDataset
    name: reddit_threads
    task: graph
    task_type: classification_binary
    transductive: false
    split_mode: cv-stratifiedkfold-8
    split_index: 6
    split_dir: datasets/splits
    node_encoder: true
    node_encoder_name: LinearNode
    node_encoder_bn: false
    edge_encoder: false

  train:
    mode: custom
    batch_size: 32
    eval_period: 1

  model:
    type: gnn
    loss_fun: weighted_cross_entropy

  gnn:
    layer_type: gcnconvweighted
    stage_type: stack
    head: weighted_mean_pool_graph
    layers_pre_mp: 0
    layers_mp: 3
    layers_post_mp: 1
    dim_inner: 128
    batchnorm: false  # true
    act: relu
    dropout: 0.0
    agg: add
    normalize_adj: false

  optim:
    clip_grad_norm: true
    optimizer: adamW
    weight_decay: 0.0
    base_lr: 0.01
    max_epoch: 50
    scheduler: cosine_with_warmup
    num_warmup_epochs: 5
