graphgym:

  accelerator: auto
  out_dir: configs_seml/results
  metric_best: accuracy
  tensorboard_each_run: false
  seed: 42

  dataset:
    format: PyG-UPFD
    name: politifact-spacy
    task: graph
    task_type: classification_binary
    transductive: false
    split_mode: standard
    node_encoder: true
    node_encoder_name: LinearNode
    node_encoder_bn: false

  train:
    mode: custom
    batch_size: 16
    eval_period: 1
    enable_ckpt: true
    ckpt_best: true

  model:
    type: gnn
    loss_fun: cross_entropy

  gnn:
    layer_type: gcnconvweighted
    stage_type: stack
    batchnorm: true
    act: relu
    dropout: 0.0
    layers_pre_mp: 0
    layers_mp: 1
    layers_post_mp: 1
    dim_inner: 64  # `gnn.dim_inner` must match `gt.dim_hidden` / `graphormer.embed_dim`
    head: weighted_add_pool_graph
  
  optim:
    base_lr: 0.0003
    weight_decay: 0.0001
    clip_grad_norm: true
    clip_grad_norm_value: 5.0
    optimizer: adamW
    max_epoch: 60
    scheduler: cosine_with_warmup
    num_warmup_epochs: 20
    early_stopping: true
    early_stopping_patience: 30
    early_stopping_delta_e: 0.05
    early_stopping_warmup: 30

  attack:
    enable: true
    log_progress: true
    load_best_model: true
    split: test
    num_attacked_graphs: 20  # 0 means attack all
    skip_incorrect_graph_classification: true
    run_random_baseline: true
    epochs: 125
    epochs_resampling: 100
    max_edge_weight_update: 0.0  # 0.0 means no gradient clipping
    lr: 4_000
    block_size: 2_000
    e_budget: 0.1
    minimum_budget: 1
    eps: 1.0e-7
    is_undirected: true
    loss: raw_prediction
    metric: null
    max_final_samples: 20
    max_trials_sampling: 20
    with_early_stopping: true
    node_prob_enable: true
    node_prob_iterations: 3
    node_prob_log: true
    remove_isolated_components: true
    root_node_idx: 0
    node_injection:
      enable: true
      from_train: true
      from_val: true
      from_test: true
      sample_only_connected: true
      # existing_node_prob_multiplier: 1  # 1_000
      sample_only_trees: true
      allow_existing_graph_pert: false
      include_root_nodes: false
