graphgym:

  out_dir: configs_seml/results
  metric_best: accuracy-SBM
  tensorboard_each_run: false
  accelerator: auto
  seed: 42

  dataset:
    format: PyG-GNNBenchmarkDataset
    name: CLUSTER
    task: graph
    task_type: classification
    transductive: false
    split_mode: standard
    node_encoder: true
    node_encoder_name: LinearNode
    node_encoder_bn: false
    edge_encoder: false

  train:
    mode: custom
    batch_size: 128
    eval_period: 1

  model:
    type: gnn
    loss_fun: weighted_cross_entropy

  gnn:
    layer_type: gatconvweighted
    att_heads: 8
    stage_type: skipsum
    head: inductive_node
    layers_pre_mp: 0
    layers_mp: 16
    layers_post_mp: 2
    dim_inner: 176
    batchnorm: true
    dropout: 0.0
    agg: mean
    normalize_adj: false

  optim:
    optimizer: adam
    weight_decay: 0.0
    base_lr: 0.001
    max_epoch: 200
    scheduler: reduce_on_plateau
    reduce_factor: 0.5
    schedule_patience: 5
    min_lr: 1.0e-5
    clip_grad_norm: false
    early_stopping: true
    early_stopping_patience: 30
    early_stopping_delta_e: 0.01
    early_stopping_warmup: 30
    
  attack:
    enable: true
    log_progress: true
    load_best_model: true
    split: test
    num_attacked_graphs: 0  # 0 means attack all
    run_random_baseline: false
    epochs: 125
    epochs_resampling: 100
    max_edge_weight_update: 0.0  # 0.0 means no gradient clipping
    lr: 4_000
    block_size: 800
    e_budget: 0.05
    minimum_budget: 0
    eps: 1.0e-7
    is_undirected: true
    prediction_level: node
    loss: tanh_margin
    metric: neg_accuracy