seml:
  executable: main.py
  output_dir: configs_seml/logs
  project_root_dir: ../..
  conda_environment: gtr

slurm:
  experiments_per_job: 2
  sbatch_options:
    partition: gpu_large
    gres: gpu:1       # num GPUs
    mem: 16G          # memory
    cpus-per-task: 4  # num cores
    time: 1-00:00     # max time, D-HH:MM

# experiment fixed configs

fixed:

  graphgym:

    accelerator: cuda
    out_dir: configs_seml/results
    metric_best: accuracy
    tensorboard_each_run: false

    dataset:
      format: PyG-UPFD
      name: politifact-bert
      task: graph
      task_type: classification_binary
      transductive: false
      split_mode: standard
      node_encoder: true
      node_encoder_name: WLapPE
      node_encoder_bn: false
      edge_encoder: true
      edge_encoder_name: WeightedSANDummyEdge
      edge_encoder_bn: false

    posenc_WLapPE:
      enable: true
      eigen:
        laplacian_norm: sym
        eigvec_norm: L2
        #max_freqs: 10
      #dim_pe: 16
      layers: 2
      n_heads: 4
      raw_norm_type: none
      post_layers: 0
      pass_as_var: false

    train:
      mode: custom
      batch_size: 32
      eval_period: 1
      enable_ckpt: true
      ckpt_best: true

    model:
      type: WeightedSANTransformer
      loss_fun: cross_entropy

    gt:
      layers: 3
      n_heads: 4
      dim_hidden: 96  # `gt.dim_hidden` must match `gnn.dim_inner`
      full_graph: true
      gamma: 0.01427
      gamma_learnable: false
      dropout: 0.0
      layer_norm: false
      batch_norm: true
      residual: true
      wsan_add_dummy_edges: true
      attn:
        use_bias: false
        clamp: null

    gnn:
      head: weighted_add_pool_graph
      layers_pre_mp: 0
      layers_post_mp: 1
      dim_inner: 96  # `gnn.dim_inner` must match `gt.dim_hidden` / `graphormer.embed_dim`
    
    optim:
      optimizer: adam
      weight_decay: 0.001
      base_lr: 0.00012874
      max_epoch: 100
      scheduler: reduce_on_plateau
      reduce_factor: 0.5
      schedule_patience: 15
      clip_grad_norm: false
      early_stopping: true
      early_stopping_patience: 35
      early_stopping_delta_e: 0.05
      early_stopping_warmup: 30

    attack:
      enable: false

grid:

  graphgym.seed:
    type: choice
    options:
      - 1
      - 2
      - 3

  graphgym.posenc_WLapPE.eigen.max_freqs:
    type: choice
    options:
      - 10
      - 30
      - 100
      - 300

  graphgym.posenc_WLapPE.dim_pe:
    type: choice
    options:
      - 16
      - 32
