seml:
  executable: main.py
  output_dir: configs_seml/logs
  project_root_dir: ../..
  conda_environment: gtr

slurm:
  experiments_per_job: 3
  sbatch_options:
    # partition: gpu_limited
    gres: gpu:1       # num GPUs
    mem: 16G          # memory
    cpus-per-task: 1  # num cores
    time: 2-00:00     # max time, D-HH:MM

# experiment fixed configs

fixed:

  graphgym:

    accelerator: cuda
    out_dir: configs_seml/results
    metric_best: accuracy
    metric_agg: argmax
    tensorboard_each_run: false

    dataset:
      format: PyG-UPFD
      name: politifact-bert
      task: graph
      task_type: classification_binary
      transductive: false
      split_mode: standard
      node_encoder: true
      node_encoder_name: LinearNode+WeightedRRWPLinear
      node_encoder_bn: false

    posenc_RRWP:
      enable: true

    train:
      mode: custom
      eval_period: 1
      # hyperparameter search, no need to save the models
      enable_ckpt: false
      batch_size: 16

    model:
      type: GritTransformer
      loss_fun: cross_entropy

    gt:
      dim_hidden: 0  # determined using num_heads and dims_per_head
      layer_norm: false
      batch_norm: true
      bn_no_runner: false  # true?
      update_e: true
      attn:
        deg_scaler: true
        use_bias: false
        clamp: 5.
        act: relu
        full_attn: true
        norm_e: true
        O_e: true
        edge_enhance: true

    gnn:
      layers_pre_mp: 0
      head: weighted_mean_pool_graph
      dim_inner: 0  # determined using num_heads and dims_per_head

    optim:
      clip_grad_norm: true
      clip_grad_norm_value: 5.0
      optimizer: adamW
      max_epoch: 200
      scheduler: cosine_with_warmup
      early_stopping: true
      early_stopping_patience: 30
      early_stopping_delta_e: 0.05
      early_stopping_warmup: 30

    attack:
      enable: false

# experiment random configs

random:
  samples: 1000
  seed: 187

  graphgym.seed:
    seed: 786
    type: randint
    min: 0
    max: 10000

  graphgym.optim.base_lr:
    seed: 2264
    type: loguniform
    min: 1e-4
    max: 2e-1

  graphgym.optim.weight_decay:
    seed: 89
    type: loguniform
    min: 1e-5
    max: 1e-1

  graphgym.gt.n_heads:
    seed: 13094
    type: randint
    min: 1
    max: 15

  dims_per_head:
    seed: 13094
    type: randint
    min: 4
    max: 50

  graphgym.gt.layers:
    seed: 357
    type: randint
    min: 1
    max: 13

  graphgym.gt.dropout:
    seed: 751
    type: choice
    options:
      - 0.0
      - 0.05
      - 0.1

  graphgym.gt.attn_dropout:
    seed: 10075
    type: uniform
    min: 0.0
    max: 0.5

  graphgym.posenc_RRWP.ksteps:
    seed: 392
    type: randint
    min: 5
    max: 22

  graphgym.posenc_RRWP.w_add_dummy_edge:
    seed: 699
    type: choice
    options:
      - true
      - false
  
  graphgym.gnn.layers_post_mp:
    seed: 96624
    type: choice
    options:
      - 1
      - 2
      - 3

  graphgym.optim.num_warmup_epochs:
    seed: 3976
    type: randint
    min: 5
    max: 20
