seml:
  executable: main.py
  output_dir: configs_seml/logs
  project_root_dir: ../..
  conda_environment: gtr

slurm:
  experiments_per_job: 8
  sbatch_options:
    partition: gpu_limited
    gres: gpu:1       # num GPUs
    mem: 16G          # memory
    cpus-per-task: 1  # num cores
    time: 1-00:00     # max time, D-HH:MM

# experiment fixed configs 

fixed:

  graphgym:

    accelerator: cuda
    out_dir: configs_seml/results
    metric_best: accuracy
    metric_agg: argmax
    tensorboard_each_run: false

    dataset:
      format: PyG-UPFD
      name: politifact-bert
      task: graph
      task_type: classification_binary
      transductive: false
      split_mode: standard
      node_encoder: true
      node_encoder_name: LinearNode+WeightedGraphormerBias
      node_encoder_bn: false

    posenc_GraphormerBias:
      enable: true
      node_degrees_only: false
      directed_graphs: false
      has_edge_attr: false
      num_out_degrees: ${config.graphgym.posenc_GraphormerBias.num_in_degrees}
      # next 2 only matter for attack, set to fixed false
      combinations_degree: false
      use_weighted_path_distance: false

    train:
      mode: custom
      eval_period: 1
      # hyperparameter search, no need to save the models
      enable_ckpt: false

    model:
      type: Graphormer
      loss_fun: cross_entropy
      graph_pooling: graph_token

    graphormer:
      dropout: 0.0
      attention_dropout: 0.0
      mlp_dropout: 0.0
      input_dropout: 0.0
      num_heads: 8

    gnn:
      layers_pre_mp: 0
      head: graphormer_graph
      dim_inner: ${config.graphgym.graphormer.embed_dim}

    optim:
      clip_grad_norm: true
      clip_grad_norm_value: 5.0
      optimizer: adamW
      max_epoch: 300
      scheduler: cosine_with_warmup
      early_stopping: true
      early_stopping_patience: 30
      early_stopping_delta_e: 0.05
      early_stopping_warmup: 30

    attack:
      enable: false

# experiment random configs

random:
  samples: 2000
  seed: 187

  graphgym.seed:
    seed: 786
    type: randint
    min: 0
    max: 10000

  graphgym.optim.base_lr:
    seed: 2264
    type: loguniform
    min: 1e-4
    max: 2e-1

  graphgym.optim.weight_decay:
    seed: 89
    type: loguniform
    min: 1e-5
    max: 1e-1

  graphgym.graphormer.embed_dim:
    seed: 13094
    type: randint
    min: 20
    max: 800

  graphgym.graphormer.num_layers:
    seed: 357
    type: choice
    type: randint
    min: 1
    max: 13

  graphgym.posenc_GraphormerBias.num_spatial_types:
    seed: 2846
    type: randint
    min: 6
    max: 15

  graphgym.posenc_GraphormerBias.num_in_degrees:
    seed: 647
    type: randint
    min: 8
    max: 41

  graphgym.train.batch_size:
    seed: 97
    type: choice
    options:
      - 8
      - 16
      - 32
      - 64
  
  graphgym.gnn.layers_post_mp:
    seed: 96624
    type: choice
    options:
      - 1
      - 2
      - 3

  graphgym.optim.num_warmup_epochs:
    seed: 3976
    type: choice
    options:
      - 5
      - 10
      - 20
