seml:
  executable: main.py
  output_dir: configs_seml/logs
  project_root_dir: ../..
  conda_environment: gtr

slurm:
  experiments_per_job: 8
  sbatch_options:
    partition: gpu_limited
    gres: gpu:1       # num GPUs
    mem: 32G          # memory
    cpus-per-task: 4  # num cores
    time: 1-00:00     # max time, D-HH:MM

# hyperparameter search

random:
  samples: 100
  seed: 187

  graphgym.seed:
    seed: 786
    type: randint
    min: 0
    max: 10000

  graphgym.optim.base_lr:
    seed: 2264
    type: loguniform
    min: 4.0e-4
    max: 1.0e-3

  graphgym.optim.weight_decay:
    seed: 89
    type: loguniform
    min: 1.0e-8
    max: 1.0e-4

  graphgym.gnn.dim_inner:
    seed: 4275
    type: randint
    min: 10
    max: 230

  graphgym.gnn.layers_mp:
    seed: 357
    type: randint
    options:
    min: 4
    max: 15
  
  graphgym.gnn.layers_post_mp:
    seed: 96624
    type: choice
    options:
      - 3
      - 4


# experiment fixed configs 

fixed:

  graphgym:

    accelerator: cuda
    out_dir: configs_seml/results
    metric_best: accuracy-SBM
    metric_agg: argmax
    tensorboard_each_run: false

    dataset:
      format: PyG-GNNBenchmarkDataset
      name: CLUSTER
      task: graph
      task_type: classification
      transductive: false
      split_mode: standard
      node_encoder: true
      node_encoder_name: LinearNode
      node_encoder_bn: false
      edge_encoder: false

    train:
      mode: custom
      batch_size: 16
      eval_period: 1

    model:
      type: gnn
      loss_fun: weighted_cross_entropy

    gnn:
      layer_type: gcnconvweighted
      stage_type: stack
      head: inductive_node
      act: relu
      agg: add
      dropout: 0.0
      layers_pre_mp: 0
      batchnorm: true
      normalize_adj: false

    optim:
      clip_grad_norm: true
      clip_grad_norm_value: 5.0
      optimizer: adamW
      max_epoch: 100
      scheduler: cosine_with_warmup
      num_warmup_epochs: 5
      early_stopping: true
      early_stopping_patience: 30
      early_stopping_delta_e: 0.02
      early_stopping_warmup: 30

    attack:
      enable: false
