seml:
  executable: main.py
  output_dir: configs_seml/logs
  project_root_dir: ../..
  conda_environment: gtr

slurm:
  experiments_per_job: 2
  sbatch_options:
    partition: gpu_large
    gres: gpu:1       # num GPUs
    mem: 16G          # memory
    cpus-per-task: 4  # num cores
    time: 1-00:00     # max time, D-HH:MM

# experiment fixed configs 

fixed:

  graphgym:

    accelerator: auto
    out_dir: configs_seml/results
    metric_best: accuracy
    metric_agg: argmax
    tensorboard_each_run: false

    dataset:
      format: PyG-RobustnessUnitTest
      name: cora_ml
      task: node
      task_type: classification
      transductive: true
      split_mode: standard
      split_index: 0
      node_encoder: true
      node_encoder_name: LinearNode+WeightedGraphormerBias
      node_encoder_bn: false

    posenc_GraphormerBias:
      enable: true
      node_degrees_only: false
      num_out_degrees: ${config.graphgym.posenc_GraphormerBias.num_in_degrees}
      directed_graphs: false
      has_edge_attr: false
      combinations_degree: false
      use_weighted_path_distance: true

    train:
      mode: custom
      batch_size: 1
      eval_period: 1
      ckpt_best: true
      enable_ckpt: true

    model:
      type: Graphormer
      loss_fun: cross_entropy

    graphormer:
      use_graph_token: false
      embed_dim: 0

    gnn:
      dim_inner: 0
      head: node
      layers_pre_mp: 0

    optim:
      clip_grad_norm: true
      clip_grad_norm_value: 5.0
      optimizer: adamW
      max_epoch: 200
      scheduler: cosine_with_warmup
      early_stopping: true
      early_stopping_patience: 30
      early_stopping_delta_e: 0.05
      early_stopping_warmup: 30

# experiment random configs

random:
  samples: 300
  seed: 187

  graphgym.seed:
    seed: 786
    type: randint
    min: 0
    max: 10000

  graphgym.optim.base_lr:
    seed: 2264
    type: loguniform
    min: 3e-5
    max: 5e-2

  graphgym.optim.weight_decay:
    seed: 89
    type: loguniform
    min: 1e-6
    max: 5e-2

  graphgym.graphormer.num_heads:
    seed: 13094
    type: randint
    min: 2
    max: 10

  dims_per_head:
    seed: 194
    type: randint
    min: 4
    max: 25

  graphgym.graphormer.num_layers:
    seed: 357
    type: randint
    min: 1
    max: 10

  # cora_ml: max cont. = 19, max total = 19
  graphgym.posenc_GraphormerBias.num_spatial_types:
    seed: 2846
    type: randint
    min: 8
    max: 20

  # cora_ml: max cont. = 19, max total = 168
  graphgym.posenc_GraphormerBias.num_in_degrees:
    seed: 647
    type: randint
    min: 8
    max: 30
  
  graphgym.gnn.layers_post_mp:
    seed: 96624
    type: choice
    options:
      - 1
      - 2
      - 3

  graphgym.optim.num_warmup_epochs:
    seed: 3976
    type: randint
    min: 5
    max: 25

  graphgym.train.homophily_regularization: 
    seed: 9734
    type: choice
    options:
      - 0.0
      - 0.5
      - 1.0
      - 1.0
      - 2.0

  graphgym.train.homophily_regularization_gt_weight:
    seed: 9734
    type: choice
    options:
      - 1.0
      - 2.0
      - 3.0

  graphgym.graphormer.dropout:
    seed: 67843
    type: uniform
    min: 0.0
    max: 0.2
  
  graphgym.graphormer.attention_dropout:
    seed: 434
    type: uniform
    min: 0.1
    max: 0.6
  
  graphgym.graphormer.mlp_dropout:
    seed: 10
    type: uniform
    min: 0.0
    max: 0.2
  
  graphgym.graphormer.input_dropout:
    seed: 5629
    type: uniform
    min: 0.0
    max: 0.2
