seml:
  executable: main.py
  output_dir: configs_seml/logs
  project_root_dir: ../..
  conda_environment: gtr

slurm:
  experiments_per_job: 1
  sbatch_options:
    partition: gpu_large
    gres: gpu:1       # num GPUs
    mem: 16G          # memory
    cpus-per-task: 4  # num cores
    time: 1-00:00     # max time, D-HH:MM

# experiment fixed configs

fixed:

  graphgym:

    accelerator: auto
    out_dir: configs_seml/results
    metric_best: accuracy
    metric_agg: argmax
    tensorboard_each_run: false

    dataset:
      format: PyG-RobustnessUnitTest
      name: cora_ml
      task: node
      task_type: classification
      transductive: true
      split_mode: standard
      split_index: 0
      node_encoder: true
      node_encoder_name: LinearNode+WeightedRRWPLinear
      node_encoder_bn: false

    posenc_RRWP:
        enable: true

    train:
      mode: custom
      batch_size: 1
      eval_period: 1
      ckpt_best: true
      enable_ckpt: true

    model:
      type: GritTransformer
      loss_fun: cross_entropy

    gt:
      dim_hidden: 0
      layer_norm: false
      batch_norm: true
      bn_no_runner: false
      bn_momentum: 0.1
      update_e: true
      attn:
        deg_scaler: true
        use_bias: false
        clamp: 5.
        act: relu
        full_attn: true
        norm_e: true
        O_e: true
        edge_enhance: true

    gnn:
      dim_inner: 0
      head: node
      layers_pre_mp: 0

    optim:
      clip_grad_norm: true
      clip_grad_norm_value: 5.0
      optimizer: adamW
      max_epoch: 200
      scheduler: cosine_with_warmup
      early_stopping: true
      early_stopping_patience: 30
      early_stopping_delta_e: 0.05
      early_stopping_warmup: 30

# experiment random configs

random:
  samples: 1000
  seed: 187

  graphgym.seed:
    seed: 786
    type: randint
    min: 0
    max: 10000

  graphgym.optim.base_lr:
    seed: 2264
    type: loguniform
    min: 3e-5
    max: 1e-2

  graphgym.optim.weight_decay:
    seed: 89
    type: loguniform
    min: 1e-6
    max: 5e-2

  graphgym.gt.n_heads:
    seed: 13094
    type: randint
    min: 2
    max: 10

  dims_per_head:
    seed: 164
    type: randint
    min: 4
    max: 25

  graphgym.gt.layers:
    seed: 357
    type: randint
    min: 1
    max: 10

  graphgym.gt.dropout:
    seed: 751
    type: uniform
    min: 0.0
    max: 0.2

  graphgym.gt.attn_dropout:
    seed: 10075
    type: uniform
    min: 0.1
    max: 0.6

  graphgym.posenc_RRWP.ksteps:
    seed: 392
    type: randint
    min: 10
    max: 25

  graphgym.posenc_RRWP.w_add_dummy_edge:
    seed: 699
    type: choice
    options:
      - true
      - false

  graphgym.gnn.layers_post_mp:
    seed: 96624
    type: choice
    options:
      - 1
      - 2
      - 3

  graphgym.optim.num_warmup_epochs:
    seed: 3976
    type: randint
    min: 3
    max: 15

  graphgym.train.homophily_regularization: 
    seed: 9734
    type: choice
    options:
      - 0.0
      - 0.5
      - 1.0
      - 1.0
      - 2.0

  graphgym.train.homophily_regularization_gt_weight:
    seed: 9734
    type: choice
    options:
      - 1.0
      - 2.0
      - 3.0
