seml:
  executable: main.py
  output_dir: configs_seml/logs
  project_root_dir: ../../../..
  conda_environment: gtr

slurm:
  experiments_per_job: 3
  sbatch_options:
    partition: gpu_gtx1080
    gres: gpu:1       # num GPUs
    mem: 16G          # memory
    cpus-per-task: 2  # num cores
    time: 1-00:00     # max time, D-HH:MM
    qos: deadline

grid:

  graphgym.attack.transfer.perturbation_path:
    type: choice
    options:
      - '/ceph/hdd/students/foth/perturbations/reddit_threads/GRIT'
      - '/ceph/hdd/students/foth/perturbations/reddit_threads/SAN'
      - '/ceph/hdd/students/foth/perturbations/reddit_threads/GCN'
      - '/ceph/hdd/students/foth/perturbations/reddit_threads/Graphormer'
      - '/ceph/hdd/students/foth/perturbations/reddit_threads/GPS'

# experiment fixed configs

fixed:

  graphgym:

    out_dir: configs_seml/results

    pretrained:
      dir: '/ceph/hdd/students/foth/models/Graphormer/reddit_threads/small'
      finetune: false

    attack:
      transfer:
        enable: true
      enable: true
      num_attacked_graphs: 0
      skip_incorrect_graph_classification: false
      log_progress: false
      load_best_model: false
      split: test
      prediction_level: graph
      remove_isolated_components: false
      run_random_baseline: false
      is_undirected: true
      root_node_idx: 0
      node_injection:
        enable: false
  
    # copied from pre-trained model
    accelerator: cuda
    bn:
      eps: 1.0e-05
      mom: 0.1
    dataset:
      cache_load: false
      cache_save: false
      dir: ./datasets
      edge_dim: 128
      edge_encoder: false
      edge_encoder_bn: true
      edge_encoder_name: Bond
      edge_encoder_num_types: 0
      edge_message_ratio: 0.8
      edge_negative_sampling_ratio: 1.0
      edge_train_mode: all
      encoder: true
      encoder_bn: true
      encoder_dim: 128
      encoder_name: db
      format: PyG-TUDataset
      infer_link_label: None
      label_column: none
      label_table: none
      location: local
      name: reddit_threads
      node_encoder: true
      node_encoder_bn: false
      node_encoder_name: LinearNode+WeightedGraphormerBias
      node_encoder_num_types: 0
      pe_transform_on_the_fly: false
      remove_feature: false
      resample_disjoint: false
      resample_negative: false
      shuffle_split: true
      slic_compactness: 10
      split:
      - 0.8
      - 0.1
      - 0.1
      split_dir: datasets/splits
      split_index: 6
      split_mode: cv-stratifiedkfold-8
      task: graph
      task_type: classification_binary
      to_undirected: false
      transductive: false
      transform: none
      tu_simple: true
    gnn:
      act: relu
      agg: add
      att_final_linear: false
      att_final_linear_bn: false
      att_heads: 1
      batchnorm: true
      clear_feature: true
      dim_inner: 48
      dropout: 0.0
      head: graphormer_graph
      keep_edge: 0.5
      l2norm: true
      layer_type: generalconv
      layers_mp: 2
      layers_post_mp: 1
      layers_pre_mp: 0
      msg_direction: single
      normalize_adj: false
      residual: false
      self_msg: concat
      skip_every: 1
      stage_type: stack
    graphormer:
      attention_dropout: 0.13840139401179627
      dropout: 0.0496090552330304
      embed_dim: 48
      input_dropout: 0.0
      mlp_dropout: 0.012110979158591462
      num_heads: 8
      num_layers: 6
      use_graph_token: true
    metric_agg: argmax
    metric_best: accuracy
    model:
      edge_decoding: dot
      graph_pooling: graph_token
      loss_fun: cross_entropy
      match_upper: true
      size_average: mean
      thresh: 0.5
      type: Graphormer
