seml:
  executable: main.py
  output_dir: configs_seml/logs
  project_root_dir: ../../../..
  conda_environment: gtr

slurm:
  experiments_per_job: 3
  sbatch_options:
    partition: gpu_large
    gres: gpu:1       # num GPUs
    mem: 16G          # memory
    cpus-per-task: 4  # num cores
    time: 1-00:00     # max time, D-HH:MM

# experiment fixed configs

fixed:

  graphgym:

    accelerator: cuda
    out_dir: configs_seml/results
    metric_best: accuracy
    tensorboard_each_run: false

    dataset:
      format: PyG-UPFD
      name: politifact-bert
      task: graph
      task_type: classification_binary
      transductive: false
      split_mode: standard
      node_encoder: true
      node_encoder_name: WLapPE
      node_encoder_bn: false
      edge_encoder: true
      edge_encoder_name: WeightedSANDummyEdge
      edge_encoder_bn: false

    posenc_WLapPE:
      enable: true
      eigen:
        laplacian_norm: sym
        eigvec_norm: L2
        max_freqs: 10
      layers: 2
      n_heads: 4
      raw_norm_type: none
      post_layers: 0
      pass_as_var: false

    train:
      mode: custom
      batch_size: 32
      eval_period: 1

    model:
      type: WeightedSANTransformer
      loss_fun: cross_entropy

    gt:
      dim_hidden: 0  # determined using num_heads and dims_per_head
      full_graph: true
      gamma_learnable: false
      layer_norm: false
      batch_norm: true
      residual: true
      attn:
        use_bias: false

    gnn:
      layers_pre_mp: 0
      dim_inner: 0  # determined using num_heads and dims_per_head
    
    optim:
      optimizer: adam
      max_epoch: 200
      scheduler: reduce_on_plateau
      reduce_factor: 0.5
      schedule_patience: 15
      clip_grad_norm: false
      early_stopping: true
      early_stopping_patience: 35
      early_stopping_delta_e: 0.05
      early_stopping_warmup: 30

    attack:
      enable: false

# experiment random configs

random:
  samples: 300
  seed: 187

  graphgym.seed:
    seed: 786
    type: randint
    min: 0
    max: 10000

  graphgym.gnn.head:
    seed: 6938
    type: choice
    options:
      - weighted_mean_pool_graph
      - weighted_add_pool_graph

  graphgym.optim.base_lr:
    seed: 2264
    type: loguniform
    min: 3e-5
    max: 3e-3

  graphgym.optim.weight_decay:
    seed: 89
    type: choice
    options:
      - 0.0
      - 0.0
      - 1e-5
      - 1e-3

  graphgym.gt.n_heads:
    seed: 13094
    type: choice
    options:
      - 4
      - 8

  dims_per_head:
    seed: 164
    type: randint
    min: 8
    max: 30

  graphgym.gt.layers:
    seed: 357
    type: randint
    min: 2
    max: 7

  graphgym.gt.dropout:
    seed: 751
    type: choice
    options:
      - 0.0
      - 0.0
      - 0.01
      - 0.05
      - 0.1

  graphgym.gt.wsan_add_dummy_edges:
    seed: 3265
    type: choice
    options:
      - true
      - false

  graphgym.gt.gamma:
    seed: 982
    type: loguniform
    min: 1e-5
    max: 1e-1

  graphgym.gt.attn.clamp:
    seed: 6424
    type: choice
    options:
      - null
      - 5.0

  graphgym.gnn.layers_post_mp:
    seed: 96624
    type: choice
    options:
      - 1
      - 2
      - 3

  graphgym.posenc_WLapPE.dim_pe:  # TODO: add option with dim per head, like for rutcoraml
    seed: 6384
    type: choice
    options:
      - 8
      - 12
      - 16

  graphgym.posenc_WLapPE.eigen.max_freqs:
    seed: 52157
      type: randint
      min: 8
      max: 60

