graphgym:

  out_dir: configs_seml/results
  metric_best: accuracy-SBM
  tensorboard_each_run: false
  accelerator: auto
  seed: 42

  dataset:
    format: PyG-GNNBenchmarkDataset
    name: CLUSTER
    task: graph
    task_type: classification
    transductive: false
    split_mode: standard
    node_encoder: true
    node_encoder_name: WLapPE  # or LinearNode+WLapPE
    node_encoder_bn: false
    edge_encoder: true
    edge_encoder_name: WeightedSANDummyEdge
    edge_encoder_bn: false

  posenc_WLapPE:
    enable: true
    eigen:
      laplacian_norm: sym
      eigvec_norm: L2
      max_freqs: 5
      eps_repeated_eigenvalue: 1.0e-5
    dim_pe: 4
    layers: 1
    n_heads: 2
    raw_norm_type: none
    post_layers: 0
    pass_as_var: false

  train:
    mode: custom
    batch_size: 3
    eval_period: 1

  model:
    type: WeightedSANTransformer
    loss_fun: weighted_cross_entropy

  gt:
    layers: 1
    n_heads: 1
    dim_hidden: 8  # `gt.dim_hidden` must match `gnn.dim_inner`
    full_graph: true
    gamma: 0.1
    gamma_learnable: true
    dropout: 0.0
    layer_norm: false
    batch_norm: true
    residual: true
    wsan_add_dummy_edges: true
    attn:
      use_bias: false
      clamp: null

  gnn:
    head: inductive_node
    layers_pre_mp: 0
    layers_post_mp: 1
    dim_inner: 8

  optim:
    optimizer: adam
    weight_decay: 0.0
    base_lr: 0.0005
    max_epoch: 1
    scheduler: reduce_on_plateau
    reduce_factor: 0.5
    schedule_patience: 10
    clip_grad_norm: false
    early_stopping: true
    early_stopping_patience: 30
    early_stopping_delta_e: 0.02
    early_stopping_warmup: 30

  attack:
    enable: true
    num_attacked_graphs: 0
    skip_incorrect_graph_classification: false
    log_progress: true
    load_best_model: false
    split: test
    prediction_level: node
    remove_isolated_components: false
    run_random_baseline: true
    e_budget: 0.05
    block_size: 500  # TODO: test
    epochs: 125  # TODO: test
    epochs_resampling: 100
    resample_period: 1  # TODO: test
    max_final_samples: 20  # TODO: test
    eps: 1.0e-07  # TODO: test
    eps_init_noised: false  # TODO: test
    is_undirected: true
    loss: tanh_margin  # TODO: test
    lr: 4000  # TODO: test
    max_edge_weight_update: 0.0  # TODO: test
    max_trials_sampling: 20
    metric: null  # TODO: add accuracy
    minimum_budget: 1
    node_prob_enable: false
    root_node_idx: null
    with_early_stopping: true
    cluster_sampling: true  # don't modify edges to labeled nodes
    node_injection:
      enable: false