graphgym:

  accelerator: auto
  out_dir: configs_seml/results
  metric_best: accuracy
  metric_agg: argmax
  tensorboard_each_run: false
  seed: 42

  dataset:
    format: PyG-Planetoid
    name: Cora
    task: node
    task_type: classification
    transductive: true
    split_mode: standard
    split_index: 0
    node_encoder: true
    node_encoder_name: WLapPE
    node_encoder_bn: false
    edge_encoder: true
    edge_encoder_name: WeightedSANDummyEdge
    edge_encoder_bn: false

  posenc_WLapPE:
    enable: true
    eigen:
      laplacian_norm: sym
      eigvec_norm: L2
      max_freqs: 10
    dim_pe: 8
    layers: 1
    n_heads: 2
    raw_norm_type: none
    post_layers: 0
    pass_as_var: false
    w_add_dummy_edge: true

  train:
    mode: custom
    batch_size: 1
    eval_period: 1
    enable_ckpt: true
    ckpt_best: true

  model:
    type: WeightedSANTransformer
    loss_fun: cross_entropy

  gt:
    layers: 1
    n_heads: 2
    dim_hidden: 32  # `gt.dim_hidden` must match `gnn.dim_inner`
    full_graph: true
    gamma: 0.01427
    gamma_learnable: false
    dropout: 0.0
    layer_norm: false
    batch_norm: true
    residual: true
    attn:
      use_bias: false
      clamp: null

  gnn:
    layers_pre_mp: 0
    layers_post_mp: 1
    dim_inner: 32  # `gnn.dim_inner` must match `gt.dim_hidden` / `graphormer.embed_dim`
  
  optim:
    optimizer: adam
    weight_decay: 0.001
    base_lr: 0.00012874
    max_epoch: 100
    scheduler: reduce_on_plateau
    reduce_factor: 0.5
    schedule_patience: 15
    clip_grad_norm: false
    early_stopping: true
    early_stopping_patience: 35
    early_stopping_delta_e: 0.05
    early_stopping_warmup: 30


  attack:
    enable: false
    log_progress: true
    load_best_model: true
    split: test
    num_attacked_graphs: 0  # 0 means attack all
    skip_incorrect_graph_classification: true
    run_random_baseline: true
    epochs: 125
    epochs_resampling: 100
    max_edge_weight_update: 0.0  # 0.0 means no gradient clipping
    lr: 4_000
    block_size: 5_000
    e_budget: 0.03
    minimum_budget: 0
    eps: 1e-7
    is_undirected: false
    prediction_level: node
    loss: tanh_margin
    metric: null
    max_final_samples: 20
    max_trials_sampling: 20
    with_early_stopping: true
    node_prob_enable: true
    node_prob_iterations: 5
    node_prob_log: true
    enable_node_injection: false
    node_injection_from_train: false
    node_injection_from_val: false
    node_injection_from_test: false
    remove_isolated_components: false
    root_node_idx: null
    include_root_nodes_for_injection: true
    existing_node_prob_multiplier: 1  # 1_000
    sample_only_connected: false
    sample_only_trees: false
    allow_existing_graph_pert: true
