graphgym:

  accelerator: auto
  out_dir: configs_seml/results
  metric_best: accuracy
  tensorboard_each_run: false
  seed: 42

  dataset:
    format: PyG-UPFD
    name: politifact-spacy
    task: graph
    task_type: classification_binary
    transductive: false
    split_mode: standard
    node_encoder: true
    node_encoder_name: WLapPE
    node_encoder_bn: false
    edge_encoder: true
    edge_encoder_name: WeightedSANDummyEdge
    edge_encoder_bn: false

  posenc_WLapPE:
    enable: true
    eigen:
      laplacian_norm: sym
      eigvec_norm: L2
      max_freqs: 10
    dim_pe: 4
    layers: 1
    n_heads: 1
    raw_norm_type: none
    post_layers: 0
    pass_as_var: false
    w_add_dummy_edge: true

  train:
    mode: custom
    batch_size: 8
    eval_period: 1
    enable_ckpt: true
    ckpt_best: true

  model:
    type: WeightedSANTransformer
    loss_fun: cross_entropy

  gt:
    layers: 1
    n_heads: 2
    dim_hidden: 8  # `gt.dim_hidden` must match `gnn.dim_inner`
    full_graph: true
    gamma: 1e-5
    gamma_learnable: false
    dropout: 0.0
    layer_norm: false
    batch_norm: true
    residual: true
    attn:
      use_bias: false
      clamp: null

  gnn:
    head: weighted_mean_pool_graph
    layers_pre_mp: 0
    layers_post_mp: 1
    dim_inner: 8  # `gnn.dim_inner` must match `gt.dim_hidden` / `graphormer.embed_dim`
  
  optim:
    optimizer: adam
    weight_decay: 0.0
    base_lr: 0.0007
    max_epoch: 1  # 1000
    scheduler: reduce_on_plateau
    reduce_factor: 0.5
    schedule_patience: 15
    clip_grad_norm: false
    early_stopping: true
    early_stopping_patience: 35
    early_stopping_delta_e: 0.05
    early_stopping_warmup: 30

  attack:
    enable: true
    num_attacked_graphs: 2
    skip_incorrect_graph_classification: false
    log_progress: true
    load_best_model: false
    split: test
    prediction_level: graph
    remove_isolated_components: true
    run_random_baseline: true
    block_size: 1_000  # TODO: test
    epochs: 125  # TODO: test
    epochs_resampling: 100
    resample_period: 1  # TODO: test
    max_final_samples: 20  # TODO: test
    eps: 1.0e-07  # TODO: test
    eps_init_noised: false  # TODO: test
    is_undirected: true
    loss: raw_prediction  # TODO: test
    metric: null
    lr: 4000  # TODO: test
    max_edge_weight_update: 0.0  # TODO: test
    max_trials_sampling: 20
    minimum_budget: 1
    node_prob_enable: true
    node_prob_iterations: 3
    node_prob_log: true
    root_node_idx: 0
    with_early_stopping: true
    node_injection:
      enable: true
      from_train: true
      from_val: true
      from_test: true
      allow_existing_graph_pert: false
      sample_only_connected: true
      include_root_nodes: false
      sample_only_trees: true
    SAN:
      add_partially_fake_edges: false
      enable_pert_grad: true
      set_first_pert_zero: true
      nia_pert: full
      match_true_signs: false
      match_true_eigenspaces: false
      pert_BPDA: false
      eps_repeated_eigenvalue: 1.0e-5
